#dtb-$(CONFIG_ARCH_QCOM)	+= apq8016-sbc.dtb msm8916-mtp.dtb
#dtb-$(CONFIG_ARCH_QCOM)	+= msm8996-mtp.dtb
#dtb-$(CONFIG_ARCH_QCOM)	+= apq8096-db820c.dtb

dtb-$(CONFIG_ARCH_SDM845) += comma_tici.dtb
dtb-$(CONFIG_ARCH_SDM845) += comma_3X.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
