/*
 * this file was generated by NunniFSMGen - do not edit!
 */


#include "include/altek_statefsm.h"
#include "include/altek_state.h"
#include "include/miniisp_ctrl.h"
#include <linux/slab.h>

#define maxfsms 1


static int initialized;
static struct altek_state altek_stateclosestate;
static struct altek_state altek_stateopenstate;
static struct altek_state altek_statehw_pass_thrustate;
static struct altek_state altek_statestandbystate;
static struct altek_state altek_stateoperationalstate;
static struct altek_state altek_statecode_persistencestate;

static struct altek_statefsm  *FSM[maxfsms];
static int fsm_size;


static int altek_stateclosestateispdrv_open(
			struct altek_statefsm *fsm, void *o)
{
	int ret = 0;

	ret = state_open(o);
	if (ret == 0)
		fsm->changestate(fsm, &altek_stateopenstate);
	return ret;
}


static int altek_stateclosestateispdrv_enter_hwpt(
			struct altek_statefsm *fsm, void *o)
{
	int ret = 0;

	ret = error_sequence(o);
	if (ret == 0)
		fsm->changestate(fsm, &altek_stateclosestate);
	return ret;
}


#define altek_stateclosestateispdrv_leave_hwpt \
			altek_stateclosestateispdrv_enter_hwpt


#define altek_stateclosestateispdrv_coldboot \
			altek_stateclosestateispdrv_enter_hwpt


#define altek_stateclosestateispdrv_scenario_chg \
			altek_stateclosestateispdrv_enter_hwpt


#define altek_stateclosestateispdrv_strm_on_off \
			altek_stateclosestateispdrv_enter_hwpt


#define altek_stateclosestateispdrv_set_qp \
			altek_stateclosestateispdrv_enter_hwpt


#define altek_stateclosestateispdrv_stop \
			altek_stateclosestateispdrv_enter_hwpt


#define altek_stateclosestateispdrv_enter_cp \
			altek_stateclosestateispdrv_enter_hwpt


#define altek_stateclosestateispdrv_leave_cp \
			altek_stateclosestateispdrv_enter_hwpt


#define altek_stateclosestateispdrv_leave_cp_standy \
			altek_stateclosestateispdrv_enter_hwpt


#define altek_stateclosestateispdrv_close \
			altek_stateclosestateispdrv_enter_hwpt


static int altek_stateopenstateispdrv_open(
			struct altek_statefsm *fsm, void *o)
{
	int ret = 0;

	ret = redundant_sequence(o);
	if (ret == 0)
		fsm->changestate(fsm, &altek_stateopenstate);
	return ret;
}


static int altek_stateopenstateispdrv_enter_hwpt(
			struct altek_statefsm *fsm, void *o)
{
	int ret = 0;

	ret = state_enter_hwpt(o);
	if (ret == 0)
		fsm->changestate(fsm, &altek_statehw_pass_thrustate);
	return ret;
}


static int altek_stateopenstateispdrv_leave_hwpt(
			struct altek_statefsm *fsm, void *o)
{
	int ret = 0;

	ret = error_sequence(o);
	if (ret == 0)
		fsm->changestate(fsm, &altek_stateopenstate);
	return ret;
}


static int altek_stateopenstateispdrv_coldboot(
			struct altek_statefsm *fsm, void *o)
{
	int ret = 0;

	ret = state_coldboot(o);
	if (ret == 0)
		fsm->changestate(fsm, &altek_statestandbystate);
	return ret;
}


#define altek_stateopenstateispdrv_scenario_chg \
			altek_stateopenstateispdrv_leave_hwpt


#define altek_stateopenstateispdrv_strm_on_off \
			altek_stateopenstateispdrv_leave_hwpt


#define altek_stateopenstateispdrv_set_qp \
			altek_stateopenstateispdrv_leave_hwpt


#define altek_stateopenstateispdrv_stop \
			altek_stateopenstateispdrv_leave_hwpt


#define altek_stateopenstateispdrv_enter_cp \
			altek_stateopenstateispdrv_leave_hwpt


#define altek_stateopenstateispdrv_leave_cp \
			altek_stateopenstateispdrv_leave_hwpt


#define altek_stateopenstateispdrv_leave_cp_standy \
			altek_stateopenstateispdrv_leave_hwpt


static int altek_stateopenstateispdrv_close(
			struct altek_statefsm *fsm, void *o)
{
	int ret = 0;

	ret = state_close(o);
	if (ret == 0)
		fsm->changestate(fsm, &altek_stateclosestate);
	return ret;
}


static int altek_statehw_pass_thrustateispdrv_open(
			struct altek_statefsm *fsm, void *o)
{
	int ret = 0;

	ret = error_sequence(o);
	if (ret == 0)
		fsm->changestate(fsm, &altek_statehw_pass_thrustate);
	return ret;
}


#define altek_statehw_pass_thrustateispdrv_enter_hwpt \
			altek_stateopenstateispdrv_enter_hwpt


static int altek_statehw_pass_thrustateispdrv_leave_hwpt(
			struct altek_statefsm *fsm, void *o)
{
	int ret = 0;

	ret = state_leave_hwpt(o);
	if (ret == 0)
		fsm->changestate(fsm, &altek_stateopenstate);
	return ret;
}


#define altek_statehw_pass_thrustateispdrv_coldboot \
			altek_stateopenstateispdrv_coldboot


static int altek_statehw_pass_thrustateispdrv_strm_on_off(
			struct altek_statefsm *fsm, void *o)
{
	int ret = 0;

	ret = error_sequence(o);
	if (ret == 0)
		fsm->changestate(fsm, &altek_statestandbystate);
	return ret;
}


#define altek_statehw_pass_thrustateispdrv_set_qp \
			altek_statehw_pass_thrustateispdrv_open


#define altek_statehw_pass_thrustateispdrv_scenario_chg \
			altek_statehw_pass_thrustateispdrv_open


#define altek_statehw_pass_thrustateispdrv_stop \
			altek_statehw_pass_thrustateispdrv_open


#define altek_statehw_pass_thrustateispdrv_enter_cp \
			altek_statehw_pass_thrustateispdrv_open


#define altek_statehw_pass_thrustateispdrv_leave_cp \
			altek_statehw_pass_thrustateispdrv_open


#define altek_statehw_pass_thrustateispdrv_leave_cp_standy \
			altek_statehw_pass_thrustateispdrv_open


#define altek_statehw_pass_thrustateispdrv_close \
			altek_stateopenstateispdrv_close


#define altek_statestandbystateispdrv_open \
			altek_statehw_pass_thrustateispdrv_strm_on_off


#define altek_statestandbystateispdrv_enter_hwpt \
			altek_statehw_pass_thrustateispdrv_strm_on_off


#define altek_statestandbystateispdrv_leave_hwpt \
			altek_statehw_pass_thrustateispdrv_strm_on_off


#define altek_statestandbystateispdrv_coldboot \
			altek_statehw_pass_thrustateispdrv_strm_on_off


static int altek_statestandbystateispdrv_scenario_chg(
			struct altek_statefsm *fsm, void *o)
{
	int ret = 0;

	ret = state_scenario_chg(o);
	if (ret == 0)
		fsm->changestate(fsm, &altek_stateoperationalstate);
	return ret;
}


static int altek_statestandbystateispdrv_strm_on_off(
			struct altek_statefsm *fsm, void *o)
{
	int ret = 0;

	ret = state_strm_on_off(o);
	if (ret == 0)
		fsm->changestate(fsm, &altek_stateoperationalstate);
	return ret;
}


#define altek_statestandbystateispdrv_set_qp \
			altek_statehw_pass_thrustateispdrv_strm_on_off


#define altek_statestandbystateispdrv_stop \
			altek_statehw_pass_thrustateispdrv_strm_on_off


static int altek_statestandbystateispdrv_enter_cp(
			struct altek_statefsm *fsm, void *o)
{
	int ret = 0;

	ret = state_enter_cp(o);
	if (ret == 0)
		fsm->changestate(fsm, &altek_statecode_persistencestate);
	return ret;
}


#define altek_statestandbystateispdrv_leave_cp \
			altek_statehw_pass_thrustateispdrv_strm_on_off


#define altek_statestandbystateispdrv_leave_cp_standy \
			altek_statehw_pass_thrustateispdrv_strm_on_off


#define altek_statestandbystateispdrv_close \
			altek_stateopenstateispdrv_close


static int altek_stateoperationalstateispdrv_open(
			struct altek_statefsm *fsm, void *o)
{
	int ret = 0;

	ret = error_sequence(o);
	if (ret == 0)
		fsm->changestate(fsm, &altek_stateoperationalstate);
	return ret;
}


#define altek_stateoperationalstateispdrv_enter_hwpt \
			altek_stateoperationalstateispdrv_open


#define altek_stateoperationalstateispdrv_leave_hwpt \
			altek_stateoperationalstateispdrv_open


#define altek_stateoperationalstateispdrv_coldboot \
			altek_stateoperationalstateispdrv_open


#define altek_stateoperationalstateispdrv_scenario_chg \
			altek_statestandbystateispdrv_scenario_chg


#define altek_stateoperationalstateispdrv_strm_on_off \
			altek_statestandbystateispdrv_strm_on_off


static int altek_stateoperationalstateispdrv_set_qp(
			struct altek_statefsm *fsm, void *o)
{
	int ret = 0;

	ret = state_set_qp(o);
	if (ret == 0)
		fsm->changestate(fsm, &altek_stateoperationalstate);
	return ret;
}


static int altek_stateoperationalstateispdrv_stop(
			struct altek_statefsm *fsm, void *o)
{
	int ret = 0;

	ret = state_stop(o);
	if (ret == 0)
		fsm->changestate(fsm, &altek_statestandbystate);
	return ret;
}


#define altek_stateoperationalstateispdrv_enter_cp \
			altek_stateoperationalstateispdrv_open


#define altek_stateoperationalstateispdrv_leave_cp \
			altek_stateoperationalstateispdrv_open


#define altek_stateoperationalstateispdrv_leave_cp_standy \
			altek_stateoperationalstateispdrv_open


#define altek_stateoperationalstateispdrv_close \
			altek_stateoperationalstateispdrv_open


static int altek_statecode_persistencestateispdrv_open(
			struct altek_statefsm *fsm, void *o)
{
	int ret = 0;

	ret = error_sequence(o);
	if (ret == 0)
		fsm->changestate(fsm, &altek_statecode_persistencestate);
	return ret;
}


static int altek_statecode_persistencestateispdrv_enter_hwpt(
			struct altek_statefsm *fsm, void *o)
{
	int ret = 0;

	ret = state_enter_hwpt(o);
	if (ret == 0)
		fsm->changestate(fsm, &altek_statecode_persistencestate);
	return ret;
}


#define altek_statecode_persistencestateispdrv_leave_hwpt \
			altek_statecode_persistencestateispdrv_open


#define altek_statecode_persistencestateispdrv_coldboot \
			altek_statecode_persistencestateispdrv_open


#define altek_statecode_persistencestateispdrv_scenario_chg \
			altek_statecode_persistencestateispdrv_open


#define altek_statecode_persistencestateispdrv_strm_on_off \
			altek_statecode_persistencestateispdrv_open


#define altek_statecode_persistencestateispdrv_set_qp \
			altek_statecode_persistencestateispdrv_open


#define altek_statecode_persistencestateispdrv_stop \
			altek_statecode_persistencestateispdrv_open


#define altek_statecode_persistencestateispdrv_enter_cp \
			altek_statecode_persistencestateispdrv_open


static int altek_statecode_persistencestateispdrv_leave_cp(
			struct altek_statefsm *fsm, void *o)
{
	int ret = 0;

	ret = state_leave_cp(o);
	if (ret == 0)
		fsm->changestate(fsm, &altek_stateoperationalstate);
	return ret;
}


static int altek_statecode_persistencestateispdrv_leave_cp_standy(
			struct altek_statefsm *fsm, void *o)
{
	int ret = 0;

	ret = state_leave_cp_standy(o);
	if (ret == 0)
		fsm->changestate(fsm, &altek_statestandbystate);
	return ret;
}


#define altek_statecode_persistencestateispdrv_close \
			altek_stateopenstateispdrv_close


int altek_statefsmispdrv_open(
			struct altek_statefsm *fsm, void *o)
{
	return fsm->m_state->ispdrv_open(fsm, o);
}


int altek_statefsmispdrv_enter_hwpt(
			struct altek_statefsm *fsm, void *o)
{
	return fsm->m_state->ispdrv_enter_hwpt(fsm, o);
}


int altek_statefsmispdrv_leave_hwpt(
			struct altek_statefsm *fsm, void *o)
{
	return fsm->m_state->ispdrv_leave_hwpt(fsm, o);
}


int altek_statefsmispdrv_coldboot(
			struct altek_statefsm *fsm, void *o)
{
	return fsm->m_state->ispdrv_coldboot(fsm, o);
}


int altek_statefsmispdrv_scenario_chg(
			struct altek_statefsm *fsm, void *o)
{
	return fsm->m_state->ispdrv_scenario_chg(fsm, o);
}


int altek_statefsmispdrv_strm_on_off(
			struct altek_statefsm *fsm, void *o)
{
	return fsm->m_state->ispdrv_strm_on_off(fsm, o);
}


int altek_statefsmispdrv_set_qp(
			struct altek_statefsm *fsm, void *o)
{
	return fsm->m_state->ispdrv_set_qp(fsm, o);
}


int altek_statefsmispdrv_stop(
			struct altek_statefsm *fsm, void *o)
{
	return fsm->m_state->ispdrv_stop(fsm, o);
}


int altek_statefsmispdrv_enter_cp(
			struct altek_statefsm *fsm, void *o)
{
	return fsm->m_state->ispdrv_enter_cp(fsm, o);
}


int altek_statefsmispdrv_leave_cp(
			struct altek_statefsm *fsm, void *o)
{
	return fsm->m_state->ispdrv_leave_cp(fsm, o);
}


int altek_statefsmispdrv_leave_cp_standy(
			struct altek_statefsm *fsm, void *o)
{
	return fsm->m_state->ispdrv_leave_cp_standy(fsm, o);
}


int altek_statefsmispdrv_close(
			struct altek_statefsm *fsm, void *o)
{
	return fsm->m_state->ispdrv_close(fsm, o);
}


void altek_statefsmchangestate(struct altek_statefsm *fsm,
			struct altek_state *newstate)
{
		fsm->m_state = newstate;
}


struct altek_statefsm *altek_statefsmcreate(void)
{
	if (fsm_size >= maxfsms)
		return 0;
	if (!initialized) {
		initialized = 1;
		altek_stateclosestate.ispdrv_open =
			altek_stateclosestateispdrv_open;
		altek_stateclosestate.ispdrv_enter_hwpt =
			altek_stateclosestateispdrv_enter_hwpt;
		altek_stateclosestate.ispdrv_leave_hwpt =
			altek_stateclosestateispdrv_leave_hwpt;
		altek_stateclosestate.ispdrv_coldboot =
			altek_stateclosestateispdrv_coldboot;
		altek_stateclosestate.ispdrv_scenario_chg =
			altek_stateclosestateispdrv_scenario_chg;
		altek_stateclosestate.ispdrv_strm_on_off =
			altek_stateclosestateispdrv_strm_on_off;
		altek_stateclosestate.ispdrv_set_qp =
			altek_stateclosestateispdrv_set_qp;
		altek_stateclosestate.ispdrv_stop =
			altek_stateclosestateispdrv_stop;
		altek_stateclosestate.ispdrv_enter_cp =
			altek_stateclosestateispdrv_enter_cp;
		altek_stateclosestate.ispdrv_leave_cp =
			altek_stateclosestateispdrv_leave_cp;
		altek_stateclosestate.ispdrv_leave_cp_standy =
			altek_stateclosestateispdrv_leave_cp_standy;
		altek_stateclosestate.ispdrv_close =
			altek_stateclosestateispdrv_close;
		altek_stateopenstate.ispdrv_open =
			altek_stateopenstateispdrv_open;
		altek_stateopenstate.ispdrv_enter_hwpt =
			altek_stateopenstateispdrv_enter_hwpt;
		altek_stateopenstate.ispdrv_leave_hwpt =
			altek_stateopenstateispdrv_leave_hwpt;
		altek_stateopenstate.ispdrv_coldboot =
			altek_stateopenstateispdrv_coldboot;
		altek_stateopenstate.ispdrv_scenario_chg =
			altek_stateopenstateispdrv_scenario_chg;
		altek_stateopenstate.ispdrv_strm_on_off =
			altek_stateopenstateispdrv_strm_on_off;
		altek_stateopenstate.ispdrv_set_qp =
			altek_stateopenstateispdrv_set_qp;
		altek_stateopenstate.ispdrv_stop =
			altek_stateopenstateispdrv_stop;
		altek_stateopenstate.ispdrv_enter_cp =
			altek_stateopenstateispdrv_enter_cp;
		altek_stateopenstate.ispdrv_leave_cp =
			altek_stateopenstateispdrv_leave_cp;
		altek_stateopenstate.ispdrv_leave_cp_standy =
			altek_stateopenstateispdrv_leave_cp_standy;
		altek_stateopenstate.ispdrv_close =
			altek_stateopenstateispdrv_close;
		altek_statehw_pass_thrustate.ispdrv_open =
			altek_statehw_pass_thrustateispdrv_open;
		altek_statehw_pass_thrustate.ispdrv_enter_hwpt =
			altek_statehw_pass_thrustateispdrv_enter_hwpt;
		altek_statehw_pass_thrustate.ispdrv_leave_hwpt =
			altek_statehw_pass_thrustateispdrv_leave_hwpt;
		altek_statehw_pass_thrustate.ispdrv_coldboot =
			altek_statehw_pass_thrustateispdrv_coldboot;
		altek_statehw_pass_thrustate.ispdrv_strm_on_off =
			altek_statehw_pass_thrustateispdrv_strm_on_off;
		altek_statehw_pass_thrustate.ispdrv_set_qp =
			altek_statehw_pass_thrustateispdrv_set_qp;
		altek_statehw_pass_thrustate.ispdrv_scenario_chg =
			altek_statehw_pass_thrustateispdrv_scenario_chg;
		altek_statehw_pass_thrustate.ispdrv_stop =
			altek_statehw_pass_thrustateispdrv_stop;
		altek_statehw_pass_thrustate.ispdrv_enter_cp =
			altek_statehw_pass_thrustateispdrv_enter_cp;
		altek_statehw_pass_thrustate.ispdrv_leave_cp =
			altek_statehw_pass_thrustateispdrv_leave_cp;
		altek_statehw_pass_thrustate.ispdrv_leave_cp_standy =
			altek_statehw_pass_thrustateispdrv_leave_cp_standy;
		altek_statehw_pass_thrustate.ispdrv_close =
			altek_statehw_pass_thrustateispdrv_close;
		altek_statestandbystate.ispdrv_open =
			altek_statestandbystateispdrv_open;
		altek_statestandbystate.ispdrv_enter_hwpt =
			altek_statestandbystateispdrv_enter_hwpt;
		altek_statestandbystate.ispdrv_leave_hwpt =
			altek_statestandbystateispdrv_leave_hwpt;
		altek_statestandbystate.ispdrv_coldboot =
			altek_statestandbystateispdrv_coldboot;
		altek_statestandbystate.ispdrv_scenario_chg =
			altek_statestandbystateispdrv_scenario_chg;
		altek_statestandbystate.ispdrv_strm_on_off =
			altek_statestandbystateispdrv_strm_on_off;
		altek_statestandbystate.ispdrv_set_qp =
			altek_statestandbystateispdrv_set_qp;
		altek_statestandbystate.ispdrv_stop =
			altek_statestandbystateispdrv_stop;
		altek_statestandbystate.ispdrv_enter_cp =
			altek_statestandbystateispdrv_enter_cp;
		altek_statestandbystate.ispdrv_leave_cp =
			altek_statestandbystateispdrv_leave_cp;
		altek_statestandbystate.ispdrv_leave_cp_standy =
			altek_statestandbystateispdrv_leave_cp_standy;
		altek_statestandbystate.ispdrv_close =
			altek_statestandbystateispdrv_close;
		altek_stateoperationalstate.ispdrv_open =
			altek_stateoperationalstateispdrv_open;
		altek_stateoperationalstate.ispdrv_enter_hwpt =
			altek_stateoperationalstateispdrv_enter_hwpt;
		altek_stateoperationalstate.ispdrv_leave_hwpt =
			altek_stateoperationalstateispdrv_leave_hwpt;
		altek_stateoperationalstate.ispdrv_coldboot =
			altek_stateoperationalstateispdrv_coldboot;
		altek_stateoperationalstate.ispdrv_scenario_chg =
			altek_stateoperationalstateispdrv_scenario_chg;
		altek_stateoperationalstate.ispdrv_strm_on_off =
			altek_stateoperationalstateispdrv_strm_on_off;
		altek_stateoperationalstate.ispdrv_set_qp =
			altek_stateoperationalstateispdrv_set_qp;
		altek_stateoperationalstate.ispdrv_stop =
			altek_stateoperationalstateispdrv_stop;
		altek_stateoperationalstate.ispdrv_enter_cp =
			altek_stateoperationalstateispdrv_enter_cp;
		altek_stateoperationalstate.ispdrv_leave_cp =
			altek_stateoperationalstateispdrv_leave_cp;
		altek_stateoperationalstate.ispdrv_leave_cp_standy =
			altek_stateoperationalstateispdrv_leave_cp_standy;
		altek_stateoperationalstate.ispdrv_close =
			altek_stateoperationalstateispdrv_close;
		altek_statecode_persistencestate.ispdrv_open =
			altek_statecode_persistencestateispdrv_open;
		altek_statecode_persistencestate.ispdrv_enter_hwpt =
			altek_statecode_persistencestateispdrv_enter_hwpt;
		altek_statecode_persistencestate.ispdrv_leave_hwpt =
			altek_statecode_persistencestateispdrv_leave_hwpt;
		altek_statecode_persistencestate.ispdrv_coldboot =
			altek_statecode_persistencestateispdrv_coldboot;
		altek_statecode_persistencestate.ispdrv_scenario_chg =
			altek_statecode_persistencestateispdrv_scenario_chg;
		altek_statecode_persistencestate.ispdrv_strm_on_off =
			altek_statecode_persistencestateispdrv_strm_on_off;
		altek_statecode_persistencestate.ispdrv_set_qp =
			altek_statecode_persistencestateispdrv_set_qp;
		altek_statecode_persistencestate.ispdrv_stop =
			altek_statecode_persistencestateispdrv_stop;
		altek_statecode_persistencestate.ispdrv_enter_cp =
			altek_statecode_persistencestateispdrv_enter_cp;
		altek_statecode_persistencestate.ispdrv_leave_cp =
			altek_statecode_persistencestateispdrv_leave_cp;
		altek_statecode_persistencestate.ispdrv_leave_cp_standy =
			altek_statecode_persistencestateispdrv_leave_cp_standy;
		altek_statecode_persistencestate.ispdrv_close =
			altek_statecode_persistencestateispdrv_close;
	}
	FSM[fsm_size] = kzalloc(sizeof(struct altek_statefsm), GFP_KERNEL);
	FSM[fsm_size]->ispdrv_open =
		altek_statefsmispdrv_open;
	FSM[fsm_size]->ispdrv_enter_hwpt =
		altek_statefsmispdrv_enter_hwpt;
	FSM[fsm_size]->ispdrv_leave_hwpt =
		altek_statefsmispdrv_leave_hwpt;
	FSM[fsm_size]->ispdrv_coldboot =
		altek_statefsmispdrv_coldboot;
	FSM[fsm_size]->ispdrv_scenario_chg =
		altek_statefsmispdrv_scenario_chg;
	FSM[fsm_size]->ispdrv_strm_on_off =
		altek_statefsmispdrv_strm_on_off;
	FSM[fsm_size]->ispdrv_set_qp =
		altek_statefsmispdrv_set_qp;
	FSM[fsm_size]->ispdrv_stop =
		altek_statefsmispdrv_stop;
	FSM[fsm_size]->ispdrv_enter_cp =
		altek_statefsmispdrv_enter_cp;
	FSM[fsm_size]->ispdrv_leave_cp =
		altek_statefsmispdrv_leave_cp;
	FSM[fsm_size]->ispdrv_leave_cp_standy =
		altek_statefsmispdrv_leave_cp_standy;
	FSM[fsm_size]->ispdrv_close =
		altek_statefsmispdrv_close;
	FSM[fsm_size]->changestate = altek_statefsmchangestate;
	FSM[fsm_size]->m_state = &altek_stateclosestate;
	return FSM[fsm_size++];
}


void altek_statefsmdelete(struct altek_statefsm *fsm)
{
	int i;
	int index = -1;

	if (fsm_size == 0 || fsm == NULL)
		return;

	for (i = 0; i < fsm_size; ++i) {
		if (FSM[i] == fsm) {
			index = i;
			break;
		}
	}

	if (index == -1)
		return;

	--fsm_size;

	if (maxfsms != 1)
		for (i = index; i < fsm_size; ++i)
			FSM[i] = FSM[i+1];

	if (fsm_size == index)
		FSM[fsm_size] = NULL;

	kfree(fsm);
}
